project_id = "uacphbmocmffhsfnxpsf"

[functions.fetch-matches]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "<client-id>"
secret = "env(VITE_SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false